import { Injectable } from "@angular/core";

Injectable({
	providedIn: "root"
})

export class Data {
  games = [
    {
      gameCover: "cover01.webp",
      gameZoom: "assets/cover/cover01.webp",
      gameTitle: "Sea of Stars Demo",
      gameLabel: "PS5 - PS4",
      gameType: "Demo",
      gamePlatformTag: "Demo",
      gamePrice: "Gratuito",
      gameReleaseDate: "29 de agosto de 2023",
    },
    {
      gameCover: "cover02.webp",
      gameZoom: "assets/cover/cover02.webp",
      gameTitle: "Hogwarts Legacy ",
      gameLabel: "PS5",
      gameType: "Standard",
      gamePlatformTag: "Standard",
      gamePrice: "R$ 299,90",
      gameReleaseDate: "10 de fevereiro de 2023",
    },
    {
      gameCover: "cover03.webp",
      gameZoom: "assets/cover/cover03.webp",
      gameTitle: "Born Of Bread",
      gameLabel: "PS5",
      gameType: "Demo",
      gamePlatformTag: "Demo",
      gamePrice: "Gratuito",
      gameReleaseDate: "10 de julho de 2023",
    },
    {
      gameCover: "cover04.webp",
      gameZoom: "assets/cover/cover04.webp",
      gameTitle: "Tower of Fantasy",
      gameLabel: "PS5",
      gameType: "Pre venda",
      gamePlatformTag: "Pre venda",
      gamePrice: "R$ 157,99",
      gameReleaseDate: "16 de dezembro de 2021",
    },
    {
      gameCover: "cover05.webp",
      gameZoom: "assets/cover/cover05.webp",
      gameTitle: "Fortnite",
      gameLabel: "PS5",
      gameType: "Standard",
      gamePlatformTag: "Standard",
      gamePrice: "Gratuito",
      gameReleaseDate: "21 de julho de 2017",
    },
    {
      gameCover: "cover06.webp",
      gameZoom: "assets/cover/cover06.webp",
      gameTitle: "ARMORED CORE™ VI FIRES OF RUBICON™",
      gameLabel: "PS4 - PS5",
      gameType: "Pre venda",
      gamePlatformTag: "Pre venda",
      gamePrice: "R$ 299,90",
      gameReleaseDate: "25 de agosto de 2023",
    },
    {
      gameCover: "cover07.webp",
      gameZoom: "assets/cover/cover07.webp",
      gameTitle: "Mortal Kombat™ 1",
      gameLabel: "PS5",
      gameType: "Pre venda",
      gamePlatformTag: "Pre venda",
      gamePrice: "R$ 469,99",
      gameReleaseDate: "19 de setembro de 2023",
    },
    {
      gameCover: "cover09.webp",
      gameZoom: "assets/cover/cover09.webp",
      gameTitle: "Boxville",
      gameLabel: "PS4 - PS5",
      gameType: "Standard",
      gamePlatformTag: "Standard",
      gamePrice: "R$ 369,99",
      gameReleaseDate: "14 de outubro de 2021",
    },
    {
      gameCover: "cover10.webp",
      gameZoom: "assets/cover/cover10.webp",
      gameTitle: "Red Dead Redemption",
      gameLabel: "PS4 - PS5",
      gameType: "Standard",
      gamePlatformTag: "Standard",
      gamePrice: "R$ 249,50",
      gameReleaseDate: "18 de maio de 2010",
    },
    {
      gameCover: "cover11.webp",
      gameZoom: "assets/cover/cover11.webp",
      gameTitle: "Legend Bowl",
      gameLabel: "PS5",
      gameType: "Pre venda",
      gamePlatformTag: "Pre venda",
      gamePrice: "R$ 369,99",
      gameReleaseDate: "27 de novembro de 2020",
    },
    {
      gameCover: "cover12.webp",
      gameZoom: "assets/cover/cover12.webp",
      gameTitle: "Spider-Man 2",
      gameLabel: "PS5",
      gameType: "Pre venda",
      gamePlatformTag: "Pre venda",
      gamePrice: "R$ 369,99",
      gameReleaseDate: "20 de outubro de 2023",
    },
    {
      gameCover: "cover13.webp",
      gameZoom: "assets/cover/cover13.webp",
      gameTitle: "Whateverland",
      gameLabel: "PS5",
      gameType: "Pre venda",
      gamePlatformTag: "Pre venda",
      gamePrice: "R$ 369,99",
      gameReleaseDate: "2022",
    },
    {
      gameCover: "cover15.webp",
      gameZoom: "assets/cover/cover15.webp",
      gameTitle: "Chants of Sennaar",
      gameLabel: "PS4 - PS5",
      gameType: "Pre venda",
      gamePlatformTag: "Pre venda",
      gamePrice: "R$ 369,99",
      gameReleaseDate: "5 de setembro de 2023",
    },
  ];
}
